server:
    port: 8082
    servlet:
        context-path: "/ead-course/"

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/ead_course
        username: postgres
        password: adm10092007
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true # aspas simples resolvem o aviso
                "[jdbc.lob.non_contextual_creation]": true
    jackson:
        serialization:
            "[INDENT_OUTPUT]": true
