server:
    port: 8888

    cloud:
        config:
            server:
                git:
                    uri: "https://github.com/jardsguimaraes/ead-config-server-repo"
                    username: ${GIT_USERNAME}
                    password: ${GIT_TOKEN}

ead:
    configServer:
        username: "${CONFIG_SERVER_USERNAME}"
        password: "${CONFIG_SERVER_PASSWORD}"
    serviceRegistry:
        username: "${SERVICE_REGISTRY_USERNAME}"
        password: "${SERVICE_REGISTRY_PASSWORD}"

encrypt:
    key: dIqOQun3edVkNcWp41BxcFRDq0lLLYf22+af/BfNPm4=
eureka:
    client:
        service-url:
            defaultZone: "http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka"
    instance:
        hostname: localhost
